name: Lint


on:
  push:
    paths:
      - '.github/workflows/lint.yml'
      - 'src/**/*.clj'
      - 'src/**/*.cljc'
    branches:
      - master
  pull_request:
    branches:
      - master


jobs:
  clj-kondo:
    name: Lint with clj-kondo
    if: "!(contains(github.event.head_commit.message, 'ci skip') || contains(github.event.head_commit.message, 'skip ci'))"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # - uses: DeLaGuardo/clojure-lint-action@f712330e03eec4daa36da7045213190083aca4dd
      #   with:
      #     clj-kondo-args: --lint src # --config .clj-kondo/config.edn
      #     # check-name is optional
      #     check-name: This is a report name
      #     github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Setup clj-kondo
        uses: DeLaGuardo/setup-clj-kondo@master
        with:
          version: '2022.03.04'
      - name: Lint
        run: |
          clj-kondo --lint src/core
          # --config .clj-kondo/config.edn
